@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
AddElementTag("old_service", $shape=RoundedBoxShape(), $bgColor="Black", $fontColor="white", $legendText="Готовый сервис")
AddElementTag("not_realise", $shape=RoundedBoxShape(), $bgColor="Grey", $fontColor="white", $legendText="Не реализовано")
AddElementTag("realise", $shape=RoundedBoxShape(), $bgColor="Green", $fontColor="white", $legendText="Реализовано")
title Yanflix Billing

LAYOUT_LANDSCAPE()

AddRelTag("red", $lineColor="red")

Container(elk, "ELK LOGS", '', $tags = "old_service")
Container(aggregator, "Aggregator API", '', $tags = "realise")

ContainerDb(queue, "Queue", 'Kafka', $tags = "old_service")
ContainerDb(queue2, "Queue", 'RabbitMQ', $tags = "old_service")

Boundary(notifications, "Сервис Нотификаций") {
    Container(notification, "Notification", 'Python', $tags = "old_service")
}

Boundary(admins, "Админ Панель") {
    Container(admin_panel, "Admin Panel", "Django", $tags = "old_service")
}

Boundary(auth_bound, "Сервис авторизации") {
    Container(auth, "Auth", 'Flask', $tags = "old_service")
}


Boundary(billing, "Сервис биллинга") {
    ContainerDb(billing_db, "Billing DB", "Postgres", $tags = "realise")
    Container(billing_api, "Billing API", 'FastAPI', $tags = "realise")
    Container(billing_scheduler, "Scheduler", 'Python', $tags = "realise")
}


Rel(billing_scheduler, billing_api, ' ')
Rel_U(billing_api,  billing_db, ' ')
Rel_L(billing_api,  elk, ' ', $tags="red")
BiRel_L(billing_api,  aggregator, ' ')
Rel(billing_api,  queue, 'Изменения подписок', $tags="red")
Rel_L(queue,  billing_api, ' Типы подписок', $tags="red")
Rel_U(billing_api,  queue2, ' ', $tags="red")

Rel(queue,  auth, ' Изменения подписок', $tags="red")
Rel_U(queue,  admin_panel, ' ', $tags="red")
Rel_D(admin_panel,  queue, 'Типы подписок', $tags="red")
Rel(queue2,  notification, 'Сообщения по успешным оплаткам', $tags="red")
Rel_L(admin_panel,  billing_db, ' Просмотр транзакций')


SHOW_LEGEND()

@enduml
