services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:6.2-alpine
    restart: always

  app:
    build: .
    volumes:
      - ./src:/code
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  worker:
    build: .
    command: python3 worker.py
    volumes:
      - ./src:/code
    depends_on:
      - app
      - redis
    env_file:
      - .env

  nginx:
    image: nginx:1.21.6
    volumes:
      - ./src/core/nginx.conf:/etc/nginx/nginx.conf
      - ./src/core/site_configs:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    restart: always