"""Added created_at to refund

Revision ID: 663505032575
Revises: e5c761cacaf7
Create Date: 2022-06-05 07:24:40.714335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663505032575'
down_revision = 'e5c761cacaf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refunds', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'refunds', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refunds', type_='unique')
    op.drop_column('refunds', 'created_at')
    # ### end Alembic commands ###
