"""Added aggregator_id

Revision ID: 667f28b403dc
Revises: 7f8cab4852cb
Create Date: 2022-05-28 15:37:21.929682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '667f28b403dc'
down_revision = '7f8cab4852cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('aggregator_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['aggregator_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'aggregator_id')
    # ### end Alembic commands ###
