"""Transaction_id in subscribe unique

Revision ID: 6917d6b7b7c3
Revises: 667f28b403dc
Create Date: 2022-05-29 09:20:41.973716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6917d6b7b7c3'
down_revision = '667f28b403dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'subscribes', ['transaction_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscribes', type_='unique')
    # ### end Alembic commands ###
