"""Added card 4 number fields

Revision ID: 7f8cab4852cb
Revises: dc7e6c5eda33
Create Date: 2022-05-26 16:22:56.924648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8cab4852cb'
down_revision = 'dc7e6c5eda33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('card_4_numbers', sa.SmallInteger()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'card_4_numbers')
    # ### end Alembic commands ###
