"""Added refunds rable

Revision ID: e5c761cacaf7
Revises: 6917d6b7b7c3
Create Date: 2022-06-05 07:17:52.182665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5c761cacaf7'
down_revision = '6917d6b7b7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('aggregator_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('transaction_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failed_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aggregator_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refunds')
    # ### end Alembic commands ###
